const crypto = require("crypto");
const fs = require("fs");
const path = require("path");
const express = require("express");
const multer = require("multer");
const rateLimit = require("express-rate-limit");
const Parse = require("parse/node");
const asyncHandler = require("../../lib/async-handler");
const { badRequest, forbidden, notFound, unauthorized } = require("../../lib/http-error");
const { config } = require("../../config/env");
const { createSession, setSessionCookie, clearSessionCookie } = require("../../services/auth.service");
const { getDashboardOverview, recordLoginActivity } = require("../../services/dashboard.service");
const {
  registerAdminSession,
  listOnlineMemberSessions,
  forceLogoutOnlineMember,
  freezeOnlineMember,
} = require("../../services/admin-session.service");
const { ensureSystemConfiguration } = require("../../services/system-configuration.service");
const {
  getOrganizationOverview,
  createOrganization,
  updateOrganization,
  deleteOrganization,
  createOrganizationMember,
  updateOrganizationMember,
  listOrganizationMembers,
} = require("../../services/organization.service");
const {
  getPositionOverview,
  createPosition,
  updatePosition,
  deletePosition,
} = require("../../services/position.service");
const { authenticate } = require("../../middleware/authenticate");
const { csrfGuard } = require("../../middleware/origin");
const logger = require("../../lib/logger");
const {
  serialize,
  getAuthContext,
  queryRecords,
  createRecord,
  updateRecord,
  deleteRecord,
  createSchema,
  updateSchema,
  removeSchema,
  listSchemaDefinitions,
  assertUserInTenant,
} = require("../../services/parse-data.service");

const router = express.Router();
const tempDirectory = path.join(config.upload.storageDir, ".tmp");

fs.mkdirSync(tempDirectory, { recursive: true });

// The filename extension is generated by the server, never copied from an
// untrusted upload. This prevents an image MIME header from storing HTML/JS
// that would later be served as an executable document on the API origin.
const uploadTypes = [
  { mimeType: "image/jpeg", extension: ".jpg", inline: true },
  { mimeType: "image/png", extension: ".png", inline: true },
  { mimeType: "image/gif", extension: ".gif", inline: true },
  { mimeType: "image/webp", extension: ".webp", inline: true },
  { mimeType: "image/avif", extension: ".avif", inline: true },
  { mimeType: "audio/mpeg", extension: ".mp3", inline: true },
  { mimeType: "audio/wav", extension: ".wav", inline: true },
  { mimeType: "audio/ogg", extension: ".ogg", inline: true },
  { mimeType: "audio/webm", extension: ".weba", inline: true },
  { mimeType: "audio/mp4", extension: ".m4a", inline: true },
  { mimeType: "video/mp4", extension: ".mp4", inline: true },
  { mimeType: "video/webm", extension: ".webm", inline: true },
  { mimeType: "video/ogg", extension: ".ogv", inline: true },
  { mimeType: "video/quicktime", extension: ".mov", inline: true },
  { mimeType: "application/pdf", extension: ".pdf", inline: false },
  { mimeType: "text/plain", extension: ".txt", inline: false },
  { mimeType: "text/csv", extension: ".csv", inline: false },
  { mimeType: "application/msword", extension: ".doc", inline: false },
  { mimeType: "application/vnd.ms-excel", extension: ".xls", inline: false },
  { mimeType: "application/vnd.ms-powerpoint", extension: ".ppt", inline: false },
  { mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document", extension: ".docx", inline: false },
  { mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", extension: ".xlsx", inline: false },
  { mimeType: "application/vnd.openxmlformats-officedocument.presentationml.presentation", extension: ".pptx", inline: false },
];
const uploadTypeByMime = new Map(uploadTypes.map((type) => [type.mimeType, type]));
const uploadTypeByExtension = new Map(uploadTypes.map((type) => [type.extension, type]));

function uploadTypeForMime(mimeType = "") {
  return uploadTypeByMime.get(mimeType.toLowerCase().trim());
}

const upload = multer({
  storage: multer.diskStorage({
    destination: tempDirectory,
    filename: (req, file, callback) => callback(null, crypto.randomUUID()),
  }),
  limits: { fileSize: config.upload.maxBytes, files: 1 },
  fileFilter: (req, file, callback) => {
    if (!uploadTypeForMime(file.mimetype)) return callback(badRequest("This file type is not allowed"));
    return callback(null, true);
  },
});

const loginLimiter = rateLimit({
  windowMs: 15 * 60 * 1000,
  limit: 10,
  standardHeaders: "draft-8",
  legacyHeaders: false,
  handler: (req, res) => {
    res.status(429).json({
      error: { code: "TOO_MANY_REQUESTS", message: "Too many login attempts. Please try again later." },
      requestId: req.requestId,
    });
  },
});

function authPayload(auth, csrfToken) {
  return {
    user: serialize(auth.user, "_User"),
    company: serialize(auth.company, "Company"),
    role: auth.role ? serialize(auth.role, "Role") : null,
    isAdmin: auth.isAdmin,
    csrfToken,
  };
}

router.get("/health", (req, res) => {
  res.json({ data: { status: "ok" }, requestId: req.requestId });
});

router.post(
  "/auth/login",
  loginLimiter,
  /**
   * 验证账号密码并建立浏览器会话，同时异步记录用户自己的登录活动。
   * @param {import("express").Request} req 含 username、password 的登录请求；不信任任何客户端租户字段。
   * @param {import("express").Response} res 写入 HttpOnly Cookie 和脱敏认证上下文的响应对象。
   * @returns {Promise<void>} 验证成功时返回认证上下文；失败时由统一错误中间件返回 400、401 或 429。
   */
  asyncHandler(async (req, res) => {
    const { username, password } = req.body || {};
    if (typeof username !== "string" || !username.trim() || typeof password !== "string" || !password) {
      throw badRequest("username and password are required");
    }

    try {
      const user = new Parse.User();
      user.set("username", username.trim());
      user.set("password", password);
      await user.logIn({ useMasterKey: true });
      const auth = await getAuthContext(user.id);
      const { token, csrfToken, sessionId } = createSession(auth.userId);
      setSessionCookie(res, token);
      try {
        await recordLoginActivity(auth, sessionId);
      } catch (activityError) {
        // 登录主流程不能因辅助统计暂时不可用而被拒绝；错误仍进入结构化日志以供运维追踪。
        logger.warn("dashboard.login_activity_unavailable", {
          requestId: req.requestId,
          userId: auth.userId,
          error: activityError.message,
        });
      }
      try {
        await registerAdminSession(auth, { sessionId }, req);
      } catch (sessionError) {
        // 会话登记是在线成员页的辅助能力，不能让已验证的登录因旧部署 Schema 尚未迁移而失败。
        logger.warn("admin_session.registration_unavailable", {
          requestId: req.requestId,
          userId: auth.userId,
          error: sessionError.message,
        });
      }
      res.json({ data: authPayload(auth, csrfToken), requestId: req.requestId });
    } catch (error) {
      if (error.status) throw error;
      throw unauthorized("Invalid username or password");
    }
  })
);

router.get(
  "/auth/session",
  authenticate,
  asyncHandler(async (req, res) => {
    res.json({ data: authPayload(req.auth, req.auth.csrf), requestId: req.requestId });
  })
);

router.post(
  "/auth/logout",
  authenticate,
  csrfGuard,
  asyncHandler(async (req, res) => {
    clearSessionCookie(res);
    res.status(204).end();
  })
);

router.use(authenticate);

router.post(
  "/system/ensure-configuration",
  csrfGuard,
  /**
   * 为当前系统管理员所在 Company 补齐 Module、Route、Schema 等基础配置，供旧数据库恢复配置入口使用。
   * @param {import("express").Request} req 已认证且通过 CSRF 校验的请求，req.auth 是服务端可信会话上下文。
   * @param {import("express").Response} res 返回幂等修复的创建与补齐摘要。
   * @returns {Promise<void>} 配置修复完成时返回 200；非管理员或数据层失败时由统一错误中间件处理。
   */
  asyncHandler(async (req, res) => {
    const result = await ensureSystemConfiguration(req.auth);
    res.json({ data: result, requestId: req.requestId });
  })
);

router.get(
  "/organization/overview",
  /**
   * 获取组织树、角色和成员范围配置；仅系统管理员可以读取完整的企业账号配置。
   * @param {import("express").Request} req 已认证请求，req.auth 由服务端会话生成。
   * @param {import("express").Response} res 返回当前 Company 的组织与成员 DTO。
   * @returns {Promise<void>} 查询成功时返回 200；非系统管理员返回 403。
   */
  asyncHandler(async (req, res) => {
    const overview = await getOrganizationOverview(req.auth);
    res.json({ data: overview, requestId: req.requestId });
  })
);

router.get(
  "/organization/members",
  /**
   * 分页读取当前企业的成员账号与组织授权范围。仅系统管理员可访问，页码、单页数量、账号检索词、
   * organizationId 和 includeDescendants 都由组织服务层规范化，避免客户端绕过租户边界。
   * @param {import("express").Request} req 已认证请求；query 可包含 page、pageSize、keyword、organizationId 与 includeDescendants。
   * @param {import("express").Response} res 返回成员 DTO、总数和当前分页信息。
   * @returns {Promise<void>} 查询成功时返回 200；无系统管理员权限或查询参数非法时返回 403/400。
   */
  asyncHandler(async (req, res) => {
    const result = await listOrganizationMembers(req.auth, req.query);
    res.json({ data: result, requestId: req.requestId });
  })
);

router.post(
  "/organization/nodes",
  csrfGuard,
  /**
   * 在当前 Company 的组织树中新增总部、区域、地方公司或部门节点。
   * @param {import("express").Request} req 已认证并通过 CSRF 校验的请求，body 是组织节点表单数据。
   * @param {import("express").Response} res 返回新建组织节点的安全 DTO。
   * @returns {Promise<void>} 新增成功时返回 201；非法上级、重复编码或权限不足时返回对应错误。
   */
  asyncHandler(async (req, res) => {
    const organization = await createOrganization(req.auth, req.body);
    res.status(201).json({ data: organization, requestId: req.requestId });
  })
);

router.put(
  "/organization/nodes/:organizationId",
  csrfGuard,
  /**
   * 修改当前 Company 的组织节点，服务端会阻止跨企业引用和父子循环。
   * @param {import("express").Request} req 已认证并通过 CSRF 校验的请求，params.organizationId 为目标节点。
   * @param {import("express").Response} res 返回更新后的组织安全 DTO。
   * @returns {Promise<void>} 更新成功时返回 200；错误由统一错误中间件转换为 HTTP 响应。
   */
  asyncHandler(async (req, res) => {
    const organization = await updateOrganization(req.auth, req.params.organizationId, req.body);
    res.json({ data: organization, requestId: req.requestId });
  })
);

router.delete(
  "/organization/nodes/:organizationId",
  csrfGuard,
  /**
   * 删除一个没有子节点且未被成员引用的空组织，避免破坏组织范围的授权依据。
   * @param {import("express").Request} req 已认证并通过 CSRF 校验的请求，params.organizationId 为目标节点。
   * @param {import("express").Response} res 删除成功时返回 204。
   * @returns {Promise<void>} 删除完成时兑现；仍被引用的组织返回 400。
   */
  asyncHandler(async (req, res) => {
    await deleteOrganization(req.auth, req.params.organizationId);
    res.status(204).end();
  })
);

router.post(
  "/organization/members",
  csrfGuard,
  /**
   * 创建子管理员或普通成员账号，并由服务端绑定 Company、主组织和可管理范围。
   * @param {import("express").Request} req 已认证并通过 CSRF 校验的请求，body 包含账号与组织范围表单。
   * @param {import("express").Response} res 返回不含密码和会话凭据的成员 DTO。
   * @returns {Promise<void>} 创建成功时返回 201；账号、密码、角色或组织范围无效时返回 400。
   */
  asyncHandler(async (req, res) => {
    const member = await createOrganizationMember(req.auth, req.body);
    res.status(201).json({ data: member, requestId: req.requestId });
  })
);

router.put(
  "/organization/members/:userId",
  csrfGuard,
  /**
   * 更新当前 Company 的成员基本资料、角色、组织范围、状态或密码；不能停用当前操作者自己。
   * @param {import("express").Request} req 已认证并通过 CSRF 校验的请求，params.userId 为目标成员标识。
   * @param {import("express").Response} res 返回更新后的脱敏成员 DTO。
   * @returns {Promise<void>} 更新成功时返回 200；越权或非法输入由统一错误中间件处理。
   */
  asyncHandler(async (req, res) => {
    const member = await updateOrganizationMember(req.auth, req.params.userId, req.body);
    res.json({ data: member, requestId: req.requestId });
  })
);

router.get(
  "/positions/overview",
  /**
   * 读取当前企业的岗位、完整页面目录和按页面可选的按钮权限。仅系统管理员可读取完整权限配置。
   * @param {import("express").Request} req 已认证请求，req.auth 为服务端可信会话上下文。
   * @param {import("express").Response} res 返回岗位列表、页面目录与权限代码。
   * @returns {Promise<void>} 查询成功时返回 200；权限不足或配置读取失败时由统一错误中间件处理。
   */
  asyncHandler(async (req, res) => {
    let overview = await getPositionOverview(req.auth);
    if (overview.needsSystemConfigurationRepair) {
      // 旧租户可能只初始化了部分 Module/Route；管理员打开岗位页时幂等补齐缺失目录并重新读取。
      await ensureSystemConfiguration(req.auth);
      overview = await getPositionOverview(req.auth);
    }
    const { needsSystemConfigurationRepair, ...safeOverview } = overview;
    res.json({ data: safeOverview, requestId: req.requestId });
  })
);

router.post(
  "/positions",
  csrfGuard,
  /**
   * 创建一个岗位，并同时设置该岗位可访问的业务页面和各页面内按钮权限。
   * @param {import("express").Request} req 已认证且通过 CSRF 校验的请求，body 含 name 和 pagePermissions。
   * @param {import("express").Response} res 返回不含内部 Pointer 或 ACL 的岗位 DTO。
   * @returns {Promise<void>} 创建成功时返回 201；岗位名称或页面权限非法时返回 400。
   */
  asyncHandler(async (req, res) => {
    const position = await createPosition(req.auth, req.body);
    res.status(201).json({ data: position, requestId: req.requestId });
  })
);

router.put(
  "/positions/:positionId",
  csrfGuard,
  /**
   * 更新普通岗位的名称、页面访问权限或逐页按钮权限；系统内置岗位不能通过该接口修改。
   * @param {import("express").Request} req 已认证且通过 CSRF 校验的请求，params.positionId 为目标岗位标识。
   * @param {import("express").Response} res 返回更新后的岗位 DTO。
   * @returns {Promise<void>} 更新成功时返回 200；系统岗位、越权或输入错误由统一错误中间件处理。
   */
  asyncHandler(async (req, res) => {
    const position = await updatePosition(req.auth, req.params.positionId, req.body);
    res.json({ data: position, requestId: req.requestId });
  })
);

router.delete(
  "/positions/:positionId",
  csrfGuard,
  /**
   * 删除未被成员引用的普通岗位，并同步清理该岗位全部授权记录。该不可逆操作由前端提供中文二次确认。
   * @param {import("express").Request} req 已认证且通过 CSRF 校验的请求，params.positionId 为待删除岗位标识。
   * @param {import("express").Response} res 删除成功时返回 204。
   * @returns {Promise<void>} 删除完成后兑现；仍被成员使用的岗位返回 400。
   */
  asyncHandler(async (req, res) => {
    await deletePosition(req.auth, req.params.positionId);
    res.status(204).end();
  })
);

router.get(
  "/dashboard/overview",
  /**
   * 返回当前会话所属用户的登录与活跃汇总，不读取客户端传入的用户或公司 ID。
   * @param {import("express").Request} req 已通过 authenticate 并带有可信 req.auth 上下文的请求对象。
   * @param {import("express").Response} res 返回数据脱敏后的仪表盘汇总对象。
   * @returns {Promise<void>} 统计成功时返回 200；会话或服务异常交给统一错误中间件处理。
   */
  asyncHandler(async (req, res) => {
    const overview = await getDashboardOverview(req.auth);
    res.json({ data: overview, requestId: req.requestId });
  })
);

router.get(
  "/online-members",
  /**
   * 查询当前企业仍有有效管理端会话的成员设备列表；所有租户与管理员边界由服务端会话决定。
   * @param {import("express").Request} req 已认证请求，req.auth 为服务端可信管理员上下文。
   * @param {import("express").Response} res 返回成员姓名、手机号、上线时间、心跳时间和设备描述。
   * @returns {Promise<void>} 查询成功返回 200；普通岗位或在线会话查询失败交给统一错误中间件。
   */
  asyncHandler(async (req, res) => {
    const result = await listOnlineMemberSessions(req.auth);
    res.json({ data: result, requestId: req.requestId });
  })
);

router.post(
  "/online-members/:userId/force-logout",
  csrfGuard,
  /**
   * 撤销目标成员的全部管理端会话；目标 JWT 在下一次 API 请求时由 authenticate 拒绝。
   * @param {import("express").Request} req 已认证并通过 CSRF 校验的请求，params.userId 为目标成员标识。
   * @param {import("express").Response} res 返回撤销的会话数量，不返回任何 Token。
   * @returns {Promise<void>} 撤销完成返回 200；越权或成员不存在返回对应错误。
   */
  asyncHandler(async (req, res) => {
    const result = await forceLogoutOnlineMember(req.auth, req.params.userId);
    res.json({ data: result, requestId: req.requestId });
  })
);

router.post(
  "/online-members/:userId/freeze",
  csrfGuard,
  /**
   * 在指定分钟内冻结目标账号并撤销其现有管理端会话，冻结状态由登录和每次认证共同校验。
   * @param {import("express").Request} req 已认证并通过 CSRF 校验的请求，body.durationMinutes 为冻结分钟数。
   * @param {import("express").Response} res 返回冻结截止时间和目标成员标识，不返回账号凭据。
   * @returns {Promise<void>} 冻结完成返回 200；时长、成员或权限非法交给统一错误中间件。
   */
  asyncHandler(async (req, res) => {
    const result = await freezeOnlineMember(req.auth, req.params.userId, req.body?.durationMinutes);
    res.json({ data: result, requestId: req.requestId });
  })
);

router.post(
  "/data/query",
  csrfGuard,
  asyncHandler(async (req, res) => {
    const result = await queryRecords(req.auth, req.body);
    res.json({ data: result, requestId: req.requestId });
  })
);

router.post(
  "/data/:className",
  csrfGuard,
  asyncHandler(async (req, res) => {
    const record = await createRecord(req.auth, req.params.className, req.body?.attributes);
    res.status(201).json({ data: record, requestId: req.requestId });
  })
);

router.put(
  "/data/:className/:id",
  csrfGuard,
  asyncHandler(async (req, res) => {
    const record = await updateRecord(req.auth, req.params.className, req.params.id, req.body?.attributes);
    res.json({ data: record, requestId: req.requestId });
  })
);

router.delete(
  "/data/:className/:id",
  csrfGuard,
  asyncHandler(async (req, res) => {
    await deleteRecord(req.auth, req.params.className, req.params.id);
    res.status(204).end();
  })
);

router.get(
  "/schema/definitions",
  asyncHandler(async (req, res) => {
    const definitions = await listSchemaDefinitions(req.auth);
    res.json({ data: definitions, requestId: req.requestId });
  })
);

router.post(
  "/schema",
  csrfGuard,
  asyncHandler(async (req, res) => {
    const result = await createSchema(req.auth, req.body);
    res.status(201).json({ data: result, requestId: req.requestId });
  })
);

router.patch(
  "/schema/:className",
  csrfGuard,
  asyncHandler(async (req, res) => {
    const result = await updateSchema(req.auth, req.params.className, req.body);
    res.json({ data: result, requestId: req.requestId });
  })
);

router.delete(
  "/schema/:className",
  csrfGuard,
  asyncHandler(async (req, res) => {
    await removeSchema(req.auth, req.params.className, req.query.purge === "true");
    res.status(204).end();
  })
);

router.post(
  "/files",
  csrfGuard,
  upload.single("file"),
  asyncHandler(async (req, res) => {
    if (!req.file) throw badRequest("A file is required");
    try {
      const uploadType = uploadTypeForMime(req.file.mimetype);
      if (!uploadType) throw badRequest("This file type is not allowed");
      const now = new Date();
      const dateParts = [
        String(now.getUTCFullYear()),
        String(now.getUTCMonth() + 1).padStart(2, "0"),
        String(now.getUTCDate()).padStart(2, "0"),
      ];
      const fileName = `${crypto.randomUUID()}${uploadType.extension}`;
      const relativePath = path.join(req.auth.userId, ...dateParts, fileName);
      const destination = path.resolve(config.upload.storageDir, relativePath);
      const storageRoot = `${path.resolve(config.upload.storageDir)}${path.sep}`;
      if (!destination.startsWith(storageRoot)) throw forbidden("Invalid file path");
      await fs.promises.mkdir(path.dirname(destination), { recursive: true });
      await fs.promises.rename(req.file.path, destination);
      res.status(201).json({
        data: {
          url: `/api/files/${req.auth.userId}/${dateParts.join("/")}/${fileName}`,
          name: req.file.originalname,
          size: req.file.size,
          mimetype: req.file.mimetype,
        },
        requestId: req.requestId,
      });
    } finally {
      // rename() removes the temporary file on success; this also cleans up
      // failed writes so a malicious or flaky upload cannot fill .tmp.
      await fs.promises.unlink(req.file.path).catch(() => {});
    }
  })
);

router.get(
  "/files/:userId/:year/:month/:day/:fileName",
  asyncHandler(async (req, res) => {
    const { userId, year, month, day, fileName } = req.params;
    if (!/^[A-Za-z0-9_-]+$/.test(userId) || !/^\d{4}$/.test(year) || !/^\d{2}$/.test(month) || !/^\d{2}$/.test(day) || !/^[a-f0-9-]+(?:\.[a-z0-9]+)?$/i.test(fileName)) {
      throw badRequest("Invalid file path");
    }
    await assertUserInTenant(req.auth, userId);
    const storageRoot = path.resolve(config.upload.storageDir);
    const filePath = path.resolve(storageRoot, userId, year, month, day, fileName);
    if (!filePath.startsWith(`${storageRoot}${path.sep}`)) throw forbidden("Invalid file path");
    if (!fs.existsSync(filePath)) throw notFound("File not found");
    const uploadType = uploadTypeByExtension.get(path.extname(fileName).toLowerCase());
    if (!uploadType) throw notFound("File not found");
    res.set({
      "Cache-Control": "private, no-store",
      "Content-Security-Policy": "sandbox; default-src 'none'; base-uri 'none'; form-action 'none'",
      "Cross-Origin-Resource-Policy": "same-origin",
      "X-Content-Type-Options": "nosniff",
    });
    if (!uploadType.inline) res.attachment(fileName);
    res.type(uploadType.mimeType);
    res.sendFile(filePath);
  })
);

module.exports = router;
